development:
  bucket_name: arts-box-development
  access_key_id: 1SDS9JGYTAD8Q561GZR2
  secret_access_key: x778REJhljF9hHVQTQS9NDtcBb9hbCy+sBfT2KxZ

testing:
  bucket_name: arts-box-testing
  access_key_id: 1SDS9JGYTAD8Q561GZR2
  secret_access_key: x778REJhljF9hHVQTQS9NDtcBb9hbCy+sBfT2KxZ
  
staging:
  bucket_name: arts-box-staging
  access_key_id: 1SDS9JGYTAD8Q561GZR2
  secret_access_key: x778REJhljF9hHVQTQS9NDtcBb9hbCy+sBfT2KxZ

production:
  bucket_name: arts-box-production
  access_key_id: 1SDS9JGYTAD8Q561GZR2
  secret_access_key: x778REJhljF9hHVQTQS9NDtcBb9hbCy+sBfT2KxZ 