development:
  bucket_name: arts-box-development
  access_key_id: 
  secret_access_key: 

testing:
  bucket_name: arts-box-testing
  access_key_id: 
  secret_access_key: 
  
staging:
  bucket_name: arts-box-staging
  access_key_id: 
  secret_access_key: 

production:
  bucket_name: arts-box-production
  access_key_id: 
  secret_access_key: